### ISSUE TITLE
Clashes when extending MenuPage while inheriting AbstractEmailForm

### ISSUE THREAD

**Issue by pyMan** [rkhleics/wagtailmenus#117]
I'm having a problem that is not strictly related to wagtailmenus but I wonder if anyone using wagtailmenus encountered the same situation.

From the wagtailmenus guide lines:
> Extend the wagtailmenus.models.MenuPage model instead of the usual wagtail.wagtailcore.models.Page to create your custom page types, and gain a couple of extra fields that will allow you to configure certain pages to appear again alongside their children in multi-level menus.

I extend all my page models from MenuPage and things work like a charm. Now I'm going to create a Page model that needs to inherit also from AbstractEmailForm

```
import copy

from wagtail.wagtailforms.models import AbstractEmailForm, AbstractFormField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, FieldRowPanel, MultiFieldPanel, InlinePanel, TabbedInterface, ObjectList
from wagtailmenus.models import MenuPage

class TestField(AbstractFormField):
    page = ParentalKey('TestPage', related_name = 'form_fields')

class TestPage(AbstractEmailForm, MenuPage):
    
    #... my fields here ...

    content_panels = copy.deepcopy(MenuPage.content_panels)
    promote_panels = copy.deepcopy(MenuPage.promote_panels)
    settings_panels = copy.deepcopy(MenuPage.settings_panels)
    
    content_panels = content_panels + [
        InlinePanel('form_fields', label = "fields"),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('from_address', classname = "col6"),
                FieldPanel('to_address', classname = "col6"),
            ]),
            FieldPanel('subject'),
        ], heading = "EMail",
    ]
    
    edit_handler = TabbedInterface([
        ObjectList(content_panels, heading="CONTENT"),
        ObjectList(promote_panels, heading="PROMOTE"),
        ObjectList(settings_panels, heading="SETTINGS", classname="settings"),
    ])

    search_fields = []
```

When executing the makemigrations command I get the following errors:

```
SystemCheckError: System check identified some issues:

ERRORS:
my_cms.TestPage.page_ptr: (fields.E304) Reverse accessor for 'TestPage.page_ptr' clashes with reverse accessor for 'TestPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'TestPage.page_ptr' or 'TestPage.page_ptr'.
my_cms.TestPage.page_ptr: (fields.E304) Reverse accessor for 'TestPage.page_ptr' clashes with reverse accessor for 'TestPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'TestPage.page_ptr' or 'TestPage.page_ptr'.
my_cms.TestPage.page_ptr: (fields.E305) Reverse query name for 'TestPage.page_ptr' clashes with reverse query name for 'TestPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'TestPage.page_ptr' or 'TestPage.page_ptr'.
my_cms.TestPage.page_ptr: (fields.E305) Reverse query name for 'TestPage.page_ptr' clashes with reverse query name for 'TestPage.page_ptr'.
        HINT: Add or change a related_name argument to the definition for 'TestPage.page_ptr' or 'TestPage.page_ptr'.
my_cms.TestPage.page_ptr: (models.E006) The field 'page_ptr' clashes with the field 'page_ptr' from model 'my_cms.testpage'.
```

This seems you cannot have a model definition that inherits twice from the Page model (like a diamond inheritance). MenuPage inherits from Page, AbstractEmailForm inherits from AbstractForm from Page.

This is a problem like [this one](https://groups.google.com/forum/#!msg/wagtail/D7j--kYtOW8/T6JVkuxcAwAJ)

I also tried a solution like the suggested one here https://github.com/wagtail/wagtail/issues/503#issuecomment-50433886 with no success (further problems come).

Python 2.7
Wagtail 1.9
Django 1.8.x
wagtailmenus 2.2.0

Thanks.
